package:
  name: lightningtrace
  version: "0.2.1"

source:
  git_url: https://github.com/GeomaticsResearch/lightningtrace.git
#  path: .

requirements:
  build:
    - python >=3
    - setuptools
    - pytest
    - rasterio
    - fiona
    - matplotlib
    - geopandas
    - shapely
  run:
    - rasterio
    - fiona
    - matplotlib
    - shapely
    - geopandas
    - python >=3

about:
  home: https://github.com/GeomaticsResearch/lightningtrace
  license: MIT
  license_file: LICENSE.txt
